### ISSUE TITLE
Windows service will start when configured with a non-admin account.

### ISSUE THREAD

**Issue by justinmetz** [fti-technology/ringtail-deploy-web#20]
If the Windows service is configured to start with a "non-admin" account (account with no local admin privs) it will still start.  The api calls that require admin access, such as installing software, will fail.  The buildOutput.txt file does not reflect lack of privileges, just general failures.

This service should only allow admin based accounts to be configured.  If one is not provided, it should fail to start.

**Comment by bmancini55** [comment]
Moved to fti-technology/ringtail-deploy-service/issues/12
