### ISSUE TITLE
Ringtail DatabaseUtility installation will hang if SQL account does not exist.

### ISSUE THREAD

**Issue by justinmetz** [fti-technology/ringtail-deploy-web#21]
Ran into this by accident when I forgot to create the SQL account that is used for the DatabaseUtility installation.  The install hangs (see picture) and the session tries to throw up the error in an interactive session.  Obviously this is user error, but I just thought I'd bring it up so it can be trapped if possible. :)
![databaseutilityrdtbug](https://cloud.githubusercontent.com/assets/12280312/8355155/844a35ac-1b1b-11e5-893f-55e1d1b99ab5.png)

**Comment by bmancini55** [comment]
Moved to fti-technology/ringtail-deploy-service/issues/11
